AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Resources:
  TasksBackendFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs22.x
      Architectures:
      - x86_64
      Events:
        TasksAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /tasks
            Method: get
      Environment:
        Variables:
          DB_USER: todo_user
          DB_HOST: ec2-13-201-76-66.ap-south-1.compute.amazonaws.com
          DB_NAME: todo
          DB_PASSWORD: hellolab
          DB_PORT: 5432
          ENABLE_MIGRATION: false
          SPLUNK_HEC_TOKEN: KKIFqEDJC6uZlQa1NhRRPA
          SPLUNK_HEC_URL: https://ingest.us1.signalfx.com

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  TasksBackendFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt TasksBackendFunction.Arn
  TasksBackendFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt TasksBackendFunctionRole.Arn
