name: Infra Terraform

on:
  push:
    branches:
      - "*"
    paths:
      - 'infra/**'
      - 'infra/*'

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}



      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.0.0

      - name: Initialize Terraform
        run: terraform init -backend-config=backend.hcl
        working-directory: ./infra

      - name: Plan Terraform
        run: terraform plan
        working-directory: ./infra

      - name: Apply Terraform
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
        working-directory: ./infra
